backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented

publish_mode: editorial_workflow

media_folder: static/img # Media files will be stored in the repo under static/img
public_folder: /img # The src attribute for uploaded media will begin with /img

collections:
  - name: "work"
  - label: "Work"
  - folder: "src/pages/work"
  - create: true
  - slug: "{{slug}}"
  - fields:
      - {label: "Headline", name: "headline", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}