backend:
  name: github
  repo: johnnycopes/rick-portfolio-new
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: static/assets # Media files will be stored in the repo under `static/assets`
public_folder: assets # The src attribute for uploaded media will begin with `assets`

collections:
  - label: "Work"
    name: "work"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "project" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Company / Product", name: "headline", widget: "string" }
      - { label: "Show in site", name: "isActive", widget: "boolean", default: true }
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - label: "Videos"
        name: "videos"
        widget: "list"
        fields: 
          - { label: "Type", name: "type", widget: "string", default: "TV" }
          - { label: "Vimeo URL", name: "url", widget: "string" }
  - label: "Pages"
    name: "pages"
    delete: false
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about" }
          - { label: "Profile Image", name: "image", widget: "image" }
          - { label: "Résumé", name: "resume", widget: "file" }
      - file: "src/pages/misc/index.md"
        label: "Misc"
        name: "misc"
        fields:
          - label: "Websites"
            name: "websites"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          - label: "Songs"
            name: "songs"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Artist", name: "artist", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          - label: "Instagrams"
            name: "instagrams"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }