backend:
  name: github
  repo: johnnycopes/rick-portfolio-new
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: static/img # Media files will be stored in the repo under static/img
public_folder: /img # The src attribute for uploaded media will begin with /img

collections:
  - name: "work"
    label: "Work"
    folder: "src/pages/work"
    identifier_field: name
    list_fields: ['title', 'headline', 'ordinal']
    list_fields_seperator: ' - '
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Company / Product", name: "headline", widget: "string" }
      - { label: "Show in site", name: "isActive", widget: "boolean", default: true }
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - label: "Videos"
        name: "videos"
        widget: "list"
        fields: 
          - label: "Videos"
            name: "videos"
            widget: "object"
            fields:
              - { label: "Type", name: "type", widget: "string", default: "TV" }
              - { label: "Vimeo URL", name: "url", widget: "string" }